steps:
  # 1. Compile and Package the Spring Boot App
  - name: maven:3.9-eclipse-temurin-21
    entrypoint: mvn
    args:
      - clean
      - test
      - package

  # 2. Build the Docker Image using the dynamic commit SHA tag
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/finova-repo/app:$COMMIT_SHA
      - .

  # 3. Push the Docker Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/$PROJECT_ID/finova-repo/app:$COMMIT_SHA

  # 4. Automatically trigger Cloud Deploy to create a brand new Release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'release-$SHORT_SHA'
      - '--delivery-pipeline=finova-pipeline'
      - '--region=asia-south1'
      - '--images=asia-south1-docker.pkg.dev/$PROJECT_ID/finova-repo/app=asia-south1-docker.pkg.dev/$PROJECT_ID/finova-repo/app:$COMMIT_SHA'

images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/finova-repo/app:$COMMIT_SHA

options:
  logging: CLOUD_LOGGING_ONLY
