apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: finova-pipeline
serialPipeline:
  stages:
  - targetId: dev-target
  - targetId: stage-target
  - targetId: prod-target
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev-target
gke:
  cluster: projects/muthukkumar/locations/asia-south1/clusters/finova-cluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: stage-target
gke:
  cluster: projects/muthukkumar/locations/asia-south1/clusters/finova-cluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-target
requireApproval: true # <-- MOVED HERE: This is the correct structural location!
gke:
  cluster: projects/muthukkumar/locations/asia-south1/clusters/finova-cluster
