apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: finova-bank-app

# 1. This is your default base configuration (usually points to dev)
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev

# 2. This defines the environment profiles Cloud Deploy is searching for
profiles:
  - name: dev-target
    manifests:
      kustomize:
        paths:
          - k8s/overlays/dev

  - name: stage-target
    manifests:
      kustomize:
        paths:
          - k8s/overlays/stage

  - name: prod-target
    manifests:
      kustomize:
        paths:
          - k8s/overlays/prod
