apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: finova-bank-app-dev
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev
---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: finova-bank-app-stage
manifests:
  kustomize:
    paths:
      - k8s/overlays/stage
---
apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: finova-bank-app-prod
manifests:
  kustomize:
    paths:
      - k8s/overlays/prod
